### ISSUE TITLE
Consider not allowing non-positive Constants to be entered - Marlowe blocks editor

### ISSUE THREAD

**Issue by BeksOmega** [input-output-hk/plutus#2902] opened 2021-03-24 20:16 UTC
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground
    - [X] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: N/A

### Description

Marlowe performs static analysis to disallow non-positive values from being deposited or paid. This is wonderful, but one advantage of blocks-based programming is that under certain circumstances, you can prevent these problems from occuring in the first place, which lessens the frustration of the user.

Blockly's number fields allow you to place [constraints](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/number#constraints) on what types of numbers can be entered. For example, only allowing for positive whole numbers, or positive numbers with up to 2 decimal places, etc. So it's definitely possible to prevent the Constants block from containing non-positive numbers, but I'm not sure if you want to.

My concern is that the Constant block is also intended to be used in arithmetic operations, in which case the user may want to use non-positive numbers. But I'm not sure what sort of contract would require this. If there's no good/common usecase I think it may be worth it to constrain the input field.

**Comment by palas** [comment] 2021-05-10 17:21
> My concern is that the Constant block is also intended to be used in arithmetic operations, in which case the user may want to use non-positive numbers. But I'm not sure what sort of contract would require this. If there's no good/common usecase I think it may be worth it to constrain the input field.

Precisely, Marlowe allows non-positive numbers as intermediate values in arithmetic operations, so even if we prevented the `Constant` construct from containing negative numbers, it would still be possible to obtain the same effect by combining it with the `NegValue` construct, for example. So static analysis is the only way to guarantee payments and deposits are non-negative in the general case. We don't currently have any example that uses non-positive constants, but we do have examples that use non-constant values: like the `Contract For differences`.

So I am claiming it is a feature, not a bug :)

**Comment by james-iohk** [comment] 2021-05-24 11:00
Closing as this is marked as `wontfix`

**Closed by james-iohk** 2021-05-24 11:00 UTC
Labels: wontfix
