### ISSUE TITLE
plutus bug report 

### ISSUE THREAD

**Issue by GenetAtakilt** [input-output-hk/plutus#896] opened 2019-04-11 08:24 UTC
we were trying to check the solution that is attached in the tutorial  for crowdfunding.
And the solution misses a couple of line of codes.
1. add 
               import Playground.Contract (mkFunctions, printSchemas)
               import Playground.Contract 
2. add      deriving (Generic, ToJSON, FromJSON, ToSchema) to data Campaign
3. add      $(mkFunctions ['scheduleCollection, 'contribute]) at the end of the solution 

After adding these lines of code it compiles but it is not working as expected. The screenshot of the error is attached below.   
![1error](https://user-images.githubusercontent.com/46132972/55942093-856c6000-5bf8-11e9-8e30-5edd466698e9.PNG)

**Comment by j-mueller** [comment] 2019-07-25 09:01
The error shows the `5fff` hash so I think this issue was also caused by #1005, which is fixed by https://github.com/input-output-hk/plutus/pull/1207.

**Closed by j-mueller** 2019-07-25 09:01 UTC
Labels: bug
