### ISSUE TITLE
Plutus-starter: EndpointNotAvailable

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#3526] opened 2021-07-09 17:20 UTC
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary
Hello I am trying to use the plutus-starter project to test out some contracts of my own, I am able to follow every step without problems until I try to interrupt with the endpoints, where it always seems to fail.

## Steps to reproduce

1. Clone 'plutus-starter`
2. Follow the steps on the `README.md` file for **VSCode devcontainer** development (Success)
3. Follow **The Plutus Application Backend (PAB) example** (Success)
4. Start both wallet instances (Success)
5. Get the status (Success)
6. Lock some value using (Fails):
```bash
curl -H "Content-Type: application/json" \
  --request POST \
  --data '{"amount":{"getValue":[[{"unCurrencySymbol":""},[[{"unTokenName":""},90]]]]},"secretWord":"eagle"}' \
  http://localhost:8080/api/new/contract/instance/$INSTANCE_ID/endpoint/lock
```
Returns error: `EndpointCallError (EndpointNotAvailable (ContractInstanceId {unContractInstanceId = 5ff489d7-4b1c-4828-afd5-424635cf87a1}) (EndpointDescription {getEndpointDescription = "lock"}))`

Btw, the discord server link has expired.

## Expected behavior
The "lock" operation was expected to go through, more info about the results I got the from the commands below

## Screenshots and attachments
`curl -s http://localhost:8080/api/new/contract/definitions | jq`

```bash
[
  {
    "csrSchemas": [
      {
        "argument": {
          "contents": [
            [
              "guessWord",
              {
                "tag": "FormSchemaString"
              }
            ]
          ],
          "tag": "FormSchemaObject"
        },
        "endpointDescription": {
          "getEndpointDescription": "guess"
        }
      },
      {
        "argument": {
          "contents": [
            [
              "secretWord",
              {
                "tag": "FormSchemaString"
              }
            ],
            [
              "amount",
              {
                "tag": "FormSchemaValue"
              }
            ]
          ],
          "tag": "FormSchemaObject"
        },
        "endpointDescription": {
          "getEndpointDescription": "lock"
        }
      }
    ],
    "csrDefinition": "GameContract"
  }
]
```
**Wallet 1**:
```bash
curl -s -H "Content-Type: application/json" \
>   --request POST \
>   --data '{"caID": "GameContract", "caWallet":{"getWallet": 1}}' \
>   http://localhost:8080/api/new/contract/activate | jq
```
Reply: 
```bash
{
  "unContractInstanceId": "5ff489d7-4b1c-4828-afd5-424635cf87a1"
}
```

Command: `export INSTANCE_ID=5ff489d7-4b1c-4828-afd5-424635cf87a1`
`curl -s http://localhost:8080/api/new/contract/instance/$INSTANCE_ID/status | jq`
```bash
{
  "cicCurrentState": {
    "observableState": [],
    "logs": [
      {
        "_logMessageContent": "Waiting for lock endpoint...",
        "_logLevel": "Info"
      },
      {
        "_logMessageContent": "Waiting for script to have a UTxO of at least 1 lovelace",
        "_logLevel": "Info"
      }
    ],
    "hooks": [],
    "err": null,
    "lastLogs": []
  },
  "cicContract": {
    "unContractInstanceId": "5ff489d7-4b1c-4828-afd5-424635cf87a1"
  },
  "cicWallet": {
    "getWallet": 1
  },
  "cicDefintion": "GameContract"
}
```

Finally: 
```bash
curl -H "Content-Type: application/json" \
  --request POST \
  --data '{"amount":{"getValue":[[{"unCurrencySymbol":""},[[{"unTokenName":""},90]]]]},"secretWord":"eagle"}' \
  http://localhost:8080/api/new/contract/instance/$INSTANCE_ID/endpoint/lock
```
Returns error: `EndpointCallError (EndpointNotAvailable (ContractInstanceId {unContractInstanceId = 5ff489d7-4b1c-4828-afd5-424635cf87a1}) (EndpointDescription {getEndpointDescription = "lock"}))`

The same happens when I try to do this for Wallet 2 and the Guess endpoint.

## Additional context
Did not change the code whatsoever, what am I doing incorrectly when interacting with the endpoints? Am I missing something?
## System info (please complete the following information):

- OS: Ubuntu
- Version  20.04]
- Plutus version or commit hash

**Comment by luigy** [comment] 2021-07-12 17:25
Thanks for the detailed report! I was able to reproduce it and put up a [fix](https://github.com/input-output-hk/plutus-starter/pull/20) for it.

**Comment by sorki** [comment] 2021-07-13 09:27
@luigy note this is about not being able to call `lock` endpoint.

I've tried this several times (prior and after [Plutus bump PR](https://github.com/input-output-hk/plutus-starter/pull/16)) hoping I can fix it but didn't figure it out. One of the things I've tried was turning ```game = lock `select` guess``` into ```game = forever $ lock `select` guess``` but that didn't help either.

**Comment by luigy** [comment] 2021-07-13 19:28
@sorki hmm that's strange. Even though "lock" endpoint is not showing up this is due to way the "guess" endpoint is currently written. I have put up a temp workaround, but there is still an underlying issue that I suspect came from #3342 that I'm currently investigating as even without my changes it is expected to work

here is a clip of me calling the "lock" endpoint with my changes
https://user-images.githubusercontent.com/817138/125512629-183bd2eb-a685-4dfd-92e8-c61dcbec5d0f.mp4

**Comment by sorki** [comment] 2021-07-16 08:35
Tested your PR and it indeed does fix this despite my intuition. If you don't mind, I would appreciate a short explanation of what is going on with `select` and endpoints in this case.

**Comment by luigy** [comment] 2021-07-17 13:15
@sorki from my understanding `select` will choose [whichever side makes progress first and discard the other](https://staging.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:select). 

`endpoint "name"` "waits" until it gets "called" externally, whereas `fundsAtAddressGeq` is "making progress" soon after given that it's a loop "receiving" responses every n slots about funds and looping again or proceeding based on the results.

> ```game = lock `select` guess```

the behavior I'm observing in the case of the game contract is that in the case of `guess`, which executes `fundsAtAddressGeq` before `endpoint`, "makes progress" first from the pov of the pab so it continues on that side and discards `lock`. This leaves the contract in a state in which is waiting for funds to increase some threshold via `fundsAtAddressGeq`, but the `lock` endpoint which is the way to "add" the funds has already been discarded.

I'm still wondering if this is the intended behavior of `fundsAtAddressGeq` with respect to `select`?

The changes in the [PR](https://github.com/input-output-hk/plutus-starter/pull/20) made `endpoint` the first thing happening in `lock` and in `guess` which results
on both waiting without any progress until either one gets called

**Comment by sorki** [comment] 2021-07-19 08:54
Thank you! Helps a lot to improve my understanding of PAB.

**Comment by gege251** [comment] 2021-07-31 09:54
@luigy @sorki I am not 100% sure, but reading the Plutus source code, I found that `fundsAtAddressGeq` waits untils it finds enough assets in the utxo map:
https://github.com/input-output-hk/plutus/blob/master/plutus-contract/src/Plutus/Contract/Request.hs#L298

When implementing the value check logic after using the `utxoAt` worked for me, but doesn't really seem necessary at all:
```haskell
  utxos <- utxoAt gameAddress

  let presentVal = Haskell.foldMap (Ledger.txOutValue . Ledger.txOutTxOut) utxos
  let cond = presentVal `Ledger.Value.geq` Ada.lovelaceValueOf 1
```

**Comment by luigy** [comment] 2021-08-25 15:11
@gege251 `fundsAtAddressGeq` stills behaves a bit funny as in it actually doesn't quite "block" as expected as it is polling on every slot for utxos, which I've improved on a bit on #3789 but still not the full solution.

With that said in https://github.com/input-output-hk/plutus-starter/pull/26 the behavior of the contract was changed to not wait on having funds any longer so now both endpoint are always available and https://github.com/input-output-hk/plutus-starter/pull/28 made it so the instance can take requests indefinitely instead of stopping after the first one is handled.

Closing this, but please reopen if you are still running into issue with the most recent version.

**Closed by luigy** 2021-08-25 15:11 UTC
Labels: bug
