### ISSUE TITLE
Expression get evaluated multiple times even with strict binding

### ISSUE THREAD

**Issue by it4rb** [input-output-hk/plutus#4645] opened 2022-05-24 04:32 UTC
### Summary

Hi Team,

The Optimization section in Plutus docs (https://plutus.readthedocs.io/en/latest/reference/optimization.html) recommends to use strict let-bindings to avoid recomputation, however in the example below I still see recomputation. Each expression only get used once and I already used strict binding so not sure what's missing here:

```
isGoodGuess :: HashedString -> ClearString -> Bool
isGoodGuess (HashedString actual) (ClearString guess') = 
    let -- 
      !x = trace "x" 0 :: Integer
      !y =  trace "y" (1, 2) :: (Integer,Integer)
      !z =  trace "z" y
      (!zz, _) = trace "zz" z
      !t = trace "t" zz

      !valid = x == t
   in valid
```

Each variable only get used once:
```
x -------------------> valid
  y -> z -> zz -> t -> valid
```
but the trace output shows that `y` get evaluated 3 times and `z` twice
`(ScriptFailure (EvaluationError ["y","y","z","y","z","zz","t","x","PT5"] "CekEvaluationFailure"))`

I've tried to replace Tuple with a custom data with strict constructor, but still getting the same results:
```
data Wrap = Wrap !Integer !Integer
PlutusTx.unstableMakeIsData ''Wrap
PlutusTx.makeLift ''Wrap

isGoodGuess :: HashedString -> ClearString -> Bool
isGoodGuess (HashedString actual) (ClearString guess') = 
    let -- 
      !x = trace "x" 0 :: Integer
      !y =  trace "y" $ Wrap 1 2
      !z =  trace "z" y
      Wrap !zz _ = trace "zz" z
      !t = trace "t" zz

      !valid = x == t
   in valid
```

I've also tried to use a more strict `trace`, still the same:
```
trace1 :: BuiltinString -> a -> a
trace1 s !x = trace s x
```

Could you please check if this is a bug or I'm doing something wrong here?

Thanks!

### Steps to reproduce the behavior

1. Go to https://playground.plutus.iohkdev.io/
2. Choose the "Game" sample
3. Replace `isGoodGuess` function with the one in the description above
4. Compile and run the simulation and observe the trace output

### Actual Result

Expressions get evaluated multiple times

### Expected Result

All expressions get evaluated only once

### System info

Plutus Playground
Same result with plutus-starter (reference commit 4127e9cd6e889824d724c30eae55033cb50cbf3e in this repo)

**Comment by michaelpj** [comment] 2022-05-24 09:19
@zliu41 could you have a look at this when you have some time?

**Comment by effectfully** [comment] 2023-01-31 22:44
This looks pretty severe, it's a shame there's been no action for almost year on this issue. I'll bring it up  to the team.

**Comment by zliu41** [comment] 2023-02-01 02:46
Sorry, I forgot to follow up on this. We should look at the PIR and try to figure out why that happened.

**Comment by effectfully** [comment] 2023-03-05 03:52
A month later, the issue is still unassigned and hasn't been worked on yet. I just wrote another message on our private slack asking for this ticket to get prioritized. I will keep you updated and sorry it's taking so long.

**Comment by michaelpj** [comment] 2023-03-08 12:01
I attempted to make a reproducer and couldn't. It's possible that your `isGoodGuess` function is getting called multiple times, it depends on how it's being used. But it doesn't look like we're miscompiling the strict bindings themselves.

**Comment by michaelpj** [comment] 2023-03-09 15:54
I'm going to close this as can't reproduce.

**Closed by michaelpj** 2023-03-09 15:54 UTC
Labels: bug, status: needs action from the team

**Comment by effectfully** [comment] 2023-03-09 16:03
@it4rb thank you for the report. If you have any additional info or ideas as to what we should've done differently to reproduce the issue, please let us know.
