### ISSUE TITLE
Bit shifting primitives

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4168] opened 2021-10-28 12:17 UTC
## Describe the feature you'd like

It would be nice to have an efficient way of exponentiating.

## Describe alternatives you've considered

Multiplying repeatedly is an alternative, but not nearly as efficient.

**Comment by effectfully** [comment] 2023-04-06 14:46
I think this can be closed as a duplicate of #4252, so I'm closing it, but please do reopen it there's something here that isn't covered by #4252.

**Closed by effectfully** 2023-04-06 14:46 UTC
Labels: enhancement, status: needs triage
