### ISSUE TITLE
Abstraction application

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1145] opened 2019-06-16 15:46 UTC
In the term reduction rules for Plutus Core (Figure 8 in the spec), we have the rule
```
{(abs \alpha K V) A} -> V
```
so instantiating an abstraction at a particular type immediately throws away the abstraction and replaces it with its body.  @jmchapman says that this breaks preservation.  

I think this goes back to the point when we introduced the value restriction (it's hard to tell because every version in the IOHK repository has this; previous versions were in Rebecca's own GitHub space).  I do have a printed version from about September 2018 that says 

```
  {(abs \alpha K M) S} -> [S/a]M
```

What should we do about this? I think we should do whatever @jmchapman says because the Agda version is supposed to be authoritative.  

There's still a question about whether the evaluator should do.  We probably shouldn't be doing anything with types during execution.  Maybe some as-yet-unproven theorem about type erasure will let us ignore them.

**Comment by wadler** [comment] 2019-06-16 22:43
I don't understand the first rule you gave---it is incorrect if x can appear free in V. Maybe it was a typo? Also, shouldn't the x be a? And the closing ] on the lhs is certainly a typo.

The second rule makes more sense to me.

**Comment by kwxm** [comment] 2019-06-17 08:52
I've changed the x to a; in the document it's actually \alpha (a type variable).

**Comment by michaelpj** [comment] 2019-06-17 09:07
I wonder if this is to match up with the description of the machine? As we discussed before, the machine implements an "erased" reduction, so it can safely do things like just go straight through abstractions.

But we probably don't want to do that for the reduction rules for Plutus Core.

**Comment by jmchapman** [comment] 2019-06-18 16:31
I think we should fix this in the machine too. In my opinion it's just wrong. Erased reduction would be erasing and then reducing. This current machine produces terms that don't type check.

**Comment by michaelpj** [comment] 2019-06-18 17:16
I think the machine can be viewed as implementing something like `evaluate :: Typed -> Erased`, and at each step it erases the argument and then evaluates it untyped. It would be great if this was formal, though.

**Comment by michaelpj** [comment] 2019-06-20 09:14
Right, it's not as simple as I said. It's a type-ignoring reduction process. And you probably need to prove that just ignoring the types is the same as erasing and then reducing.

**Comment by jmchapman** [comment] 2019-06-20 09:19
I think the problem is that it is not the same if you don’t reduce under lambda. You ignore some of the types but not all, and those that remain can refer to unbound type variables and therefore the whole term can be ill-typed.

**Comment by michaelpj** [comment] 2019-06-20 09:33
Verily:
```
michael@clipper:~/projects/iohk/plutus ❯ echo "(program 1.0.0 {(abs a (type) (lam x a x)) (con integer)})" | result/bin/plc evaluate --stdin
(lam x a x)
```

**Comment by michaelpj** [comment] 2020-01-15 10:30
We fixed this in the spec, I think the remaining issue will be proving that what the machines do is correct, which I'm happy to leave to James to worry about when he gets to it ;)

**Closed by michaelpj** 2020-01-15 10:30 UTC
Labels: Metatheory, Plutus Core, Spec
