### ISSUE TITLE
Fixed point arithmetic and `Data.Fixed`

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/plutus#4275] opened 2021-12-08 22:21 UTC
## Describe the feature you'd like

Haskell has long enjoyed convenient fixed point arithmetic with `Data.Fixed`.

However, we cannot use `Data.Fixed` cannot use parametric precision at the moment, since the type with kinded argument is not supported.

## Describe alternatives you've considered

Alternatives considered are:

* request support for kinded argument
* template haskell derivation of alternative `Data.Fixed` for each resolution
* manually implement each case

## Describe the approach you would take to implement this 

Since fixed point arithmetic comes in many financial applications, I would like suggestions on the best way to tackle this problem in the long run.

## Additional context / screenshots

* `Ledger.Ada` datatype is best example of how each such type needs to be implemented manually.

**Comment by michaelpj** [comment] 2021-12-09 10:08
Yeah, it's annoying that `Data.Fixed` is poly-kinded. That won't be supported any time soon. Manually implementing the N versions might be the simplest solution.

**Comment by effectfully** [comment] 2023-01-31 23:28
Closing as a duplicate of #4537.

**Closed by effectfully** 2023-01-31 23:28 UTC
Labels: enhancement
