### ISSUE TITLE
Function for the on-chain size of a CompiledCode

### ISSUE THREAD

**Issue by kozross** [input-output-hk/plutus#4314] opened 2022-01-05 20:17 UTC
### Describe the feature you'd like

This pertains to adding the ([already-written](https://github.com/Liqwid-Labs/plutus-extra/tree/master/plutus-numeric/test)) tests to #4284. A significant part of the testing ensures that the on-chain sizes of various functions stays with certain bounds. This can help ensure two things:

1. Our functions fit on-chain as-such; and
2. We don't regress on size.

MLabs have an [existing library](https://github.com/Liqwid-Labs/plutus-extra/tree/master/plutus-size-check) for doing this kind of size checking using `tasty`, since the method of getting accurate on-chain sizes is [a bit non-trivial](https://github.com/Liqwid-Labs/plutus-extra/blob/master/plutus-size-check/src/Test/Tasty/Plutus/Size.hs#L261). Many of the improvements made in #4284 were discovered, and refined, using this tool.

Since there has been a [request to upstream our tests](https://github.com/input-output-hk/plutus/pull/4284#discussion_r778775751), it would be nice to have anti-regression size checks included as well. To make this easier, it would be good to have a function like

```onChainSize :: forall (a :: Type) . CompiledCode a -> Int```

This would serve the same purpose as [this functionality](https://github.com/Liqwid-Labs/plutus-extra/blob/master/plutus-size-check/src/Test/Tasty/Plutus/Size.hs#L261), and would mean it doesn't have to be reimplemented in multiple places. We also believe having this built-in would be more generally useful, as the size limitations imposed on-chain are a significant restriction, and being able to more conveniently examine and test for this without having to repeat our work would be an advantage.

### Describe alternatives you've considered

For this specific case, we could reimplement all the functionality (more or less) in `plutus-check-size`, or not port the size tests. We believe both of these are poor choices: if we were to do the first, it seems like a huge waste not to have this functionality more generally available; the second simply reduces our test coverage for no good reason. More generally, there's no reason why anyone else _couldn't_ reimplement our method, but it seems like a waste once again, especially since it's not exactly trivial to discover.

**Comment by michaelpj** [comment] 2022-01-06 11:58
> since the method of getting accurate on-chain sizes is a bit non-trivial.

Wow, I didn't realise there was all this extra wrapping in the ledger. That does seem annoying. Unfortunately we can't include that here since it depends on `cardano-api`. However, for regression testing purposes I _think_ you only really care about having a measure that's proportional to the final size, for that you could either:
- Just `serialise` the `Script` (I assume the extra wrapping just adds a tag or so of overhead)
- Use `scriptSize`, which counts the size of the AST, which would also work as a measure proportional to the final size

Of course, those won't work if you want to test a real script for its real size, but there I think there's probably no alternative to going via `cardano-api`.

**Comment by kozross** [comment] 2022-01-06 18:04
In that case, I don't think anything else needs to be added. This won't be as good as the precise measures we can get from our library, but as you said, for regression-proofing, it's reasonable enough.

**Comment by michaelpj** [comment] 2022-01-10 14:41
Okay, then I'll close this.

**Closed by michaelpj** 2022-01-10 14:41 UTC
Labels: enhancement
