### ISSUE TITLE
Are `awaitSlot` and `fundsAtAddressGt` incompatible?

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#3005] opened 2021-04-14 11:51 UTC
Hello, I am trying to implement an Auction Smart Contract and compile in using the Plutus Playground (https://playground.plutus.iohkdev.io/)

I have not completed the logic of the auction yet but in the first version I just wanted to test if I could have some sort of "trigger" that when the buy now clause was activated or the time for the auction ran out the money would be automatically collected (this is done by changing the state of the state machine)

Unfortunately I am facing two problems right now:

1. This is the most important for me currently, to automatically change the status of the Auction to finished I am trying to utilize the following line of code:
```hs
outcome <- mapError (review _AuctionError) $ selectEither (awaitSlot deadline) (fundsAtAddressGt contractAddress (Ada.lovelaceValueOf maxBidValue))
```
When the maximum value is reached the contract behaves as expected (the person who initialized the auction retrieves the money), as the screenshots below show (simulation is present on the gist linked below)
![Screenshot from 2021-04-14 12-45-11](https://user-images.githubusercontent.com/48067609/114705123-4c06e780-9d1f-11eb-9c44-cc563cced8b5.png)
![Screenshot from 2021-04-14 12-45-48](https://user-images.githubusercontent.com/48067609/114705184-5d4ff400-9d1f-11eb-8c09-9f68b8d4d91a.png)

Unfortunately the same cannot be said for the situation where the auction exceeds the deadline. When this is the case nothing appears to happen:
![Screenshot from 2021-04-14 12-47-43](https://user-images.githubusercontent.com/48067609/114705416-a1db8f80-9d1f-11eb-9f88-ac7c259b0c1e.png)
![Screenshot from 2021-04-14 12-47-21](https://user-images.githubusercontent.com/48067609/114705374-94260a00-9d1f-11eb-914e-aeb52d669e93.png)

I have tried to use the `selectEither` function for two slots and it works like a charm.
Therefore I concluded that it's probably some incompatibility between the two types of event.
Anyway is there anything that I can do to fix this problem? It would be very appreciated any help regarding this subject

2. For some reason the maxBidValue parameter for `initialise` endpoint always has 0 has it's values (to work around this I am just using fixed values for the trigger above). This doesn't happen in the bid endpoint or in any other contract I have programmed. What am I missing in this case?

The gist for the code of the contract is linked below, thank you very much for your time and attention

Diagnostic info:
- I was using the:
    - [x] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 
https://gist.github.com/LendaDeAfonselio/3ffdf3e25d4d017550f771b81f11b540

**Comment by j-mueller** [comment] 2021-04-16 06:51
There are some issues with the functions in `Plutus.Contract.Effects.AwaitSlot` and `Plutus.Contract.Effects.UtxoAt`. The cause of this is that the API currently doesn't separate waiting actions (`awaitSlot`, `endpoint`, etc) from non-waiting actions (`utxoAt`, `currentSlot`, etc) very well. I'm working on a fix for this.

**Comment by ak3n** [comment] 2021-08-10 06:48
@j-mueller have these issues been fixed?

**Comment by j-mueller** [comment] 2021-08-11 09:27
@ak3n : Yes, with https://github.com/input-output-hk/plutus/pull/3558 you now can't write `selectEither` on `awaitSlot` and `fundsAtAddressGt` anymore

**Closed** 2021-08-11 09:29 UTC
Labels: bug, Contract API
