### ISSUE TITLE
Missing dependency during build when project depends on new version of plutus

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#4433] opened 2022-02-28 11:03 UTC
### Summary

i'm trying to depend on recent plutus commit: 61a9a0fbeae5eaf944e9e09e47c0a42fe5cb2c2a
But I get this error on build of the project:

```
cabal: sdist of plutus-metatheory-0.1.0.0: Error: Could not find module:
MAlonzo.Code.Declarative with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

I've copied the plutus's cabal.project to mine, and updated the libs according to the specified versions.

### Steps to reproduce the behavior

Create project that depends on plutus and try to build it (plutus commit: 61a9a0fbeae5eaf944e9e09e47c0a42fe5cb2c2a).

### Actual Result

`nix-shell` opens fine but when I try to build my project I get the error:

```
cabal: sdist of plutus-metatheory-0.1.0.0: Error: Could not find module:
MAlonzo.Code.Declarative with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

### Expected Result

Successful build

### System info

Manjaro

**Comment by michaelpj** [comment] 2022-02-28 12:19
I don't know why whatever you're doing requires you to `sdist` `plutus-metatheory`, it shouldn't.

**Comment by michaelpj** [comment] 2022-02-28 12:19
Also, dupe of the issue you already opened??

**Closed by michaelpj** 2022-02-28 12:19 UTC
Labels: bug
