### ISSUE TITLE
Reference to a name which is not ...: Variable PlutusTx.Eq.$fEqByteString

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3613] opened 2021-07-26 15:28 UTC
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

```
# Checkout Plutus version referenced by Alonzo-testnet
> cd .../plutus; git checkout 523f349f3d68db07c98150734793ed7003d1f562

# Start a Nix shell
> nix-shell

# Change to .../Alonzo-testnet/resources/plutus-sources
> cd .../plutus-sources

# Build the sources
> cabal build plutus-helloworld

# The above should work. Now try a HLS build, like an IDE would
> haskell-language-server-wrapper plutus-helloworld

2021-07-26 17:24:56.310973 [ThreadId 397] INFO hls:	File:    
  .../plutus-sources/plutus-helloworld/src/Cardano/PlutusExample/HelloWorldByteStringParametric.hs
Hidden:   no
Range:    1:1-2:1
Source:   compile
Severity: DsError
Message: 
  Program error: GHC Core to PLC plugin: E043:Error: Reference to a name which is not a local, a
  builtin, or an external INLINABLE function: Variable PlutusTx.Eq.$fEqByteString
  [DFunId(nt)]
  No unfolding
  Context: Compiling expr: PlutusTx.Eq.$fEqByteString
  Context: Compiling expr: PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool))
  Context: Compiling expr: (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword
  Context: Compiling expr: (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword datum
  Context: Compiling expr: \ _ [Occ=Dead] ->
  (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword datum
  Context: Compiling expr: \ _ [Occ=Dead] _ [Occ=Dead] ->
  (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword datum
  Context: Compiling expr: \ (datum [Occ=Once]
  :: Data.ByteString.Internal.ByteString)
  _ [Occ=Dead]
  _ [Occ=Dead] ->
  (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword datum
  Context: Compiling expr: \ (keyword [Occ=Once]
  :: Data.ByteString.Internal.ByteString)
  (datum [Occ=Once] :: Data.ByteString.Internal.ByteString)
  _ [Occ=Dead]
  _ [Occ=Dead] ->
  (PlutusTx.Eq.$fEqByteString
  `cast` (PlutusTx.Eq.N:Eq[0] <Data.ByteString.Internal.ByteString>_N
  :: GHC.Types.Coercible
  (PlutusTx.Eq.Eq Data.ByteString.Internal.ByteString)
  (Data.ByteString.Internal.ByteString
  -> Data.ByteString.Internal.ByteString -> GHC.Types.Bool)))
  keyword datum
  Context: Compiling definition of: Cardano.PlutusExample.HelloWorldByteStringParametric.helloWorld
  Context: Compiling expr: Cardano.PlutusExample.HelloWorldByteStringParametric.helloWorld
  Context: Compiling expr at
  "main:Cardano.PlutusExample.HelloWorldByteStringParametric:(60,9)-(60,44)"
```

**Comment by ak3n** [comment] 2021-07-27 06:40
Hi! Thanks for reporting!

I'm closing this one as a duplicate of #3454.

**Closed by ak3n** 2021-07-27 06:40 UTC
Labels: bug
