### ISSUE TITLE
Function producing compiled script fails if is not exported

### ISSUE THREAD

**Issue by uhbif19** [input-output-hk/plutus#5355] opened 2023-05-24 18:06 UTC
### Summary

We have function returning compiled script. It crashes if we call it. Script does not matter.

Script compilation do not break exactly if:

* Function signature has HasCallStack
* Function is exported
* Function is used for compilation of another script, that is exported
* It is not function, but term (has no arguments)

### Steps to reproduce the behavior

Minimal code example so far:

```
scriptValidatorForTerms :: AuctionScript -> AuctionTerms -> SerialisedScript
scriptValidatorForTerms Deposit = depositValidator

{-# INLINEABLE depositValidator #-}
depositValidator :: SerialisedScript
depositValidator =
  serialiseCompiledCode $
    $$(PlutusTx.compile [||wrapValidator . func||])

  where
    func ::
      Prelude.Integer
      -> Prelude.Integer -> Prelude.Integer -> Prelude.Integer -> Bool
    func _ _ _ _ = True
  ```
   Calling `show $ scriptValidatorForTerms Deposit undefined` raises exception.

### Actual Result

If depositValidator is exported - it works. If not - calling scriptValidatorForTerms Deposit undefined will raise:
"*** Exception: This must be replaced by the core-to-plc plugin during compilation: plc
CallStack (from HasCallStack):
  error, called at src/PlutusTx/Utils.hs:8:26 in plutus-tx-1.1.1.0-8fuGrqxACC7A8obj3qrZvt
  

### Expected Result

Serialized script.

### System info

plutus-tx-plugin ==1.1.0.0
GHC version: 8.10.7

All options from troubleshooting seems to be enabled.

**Comment by uhbif19** [comment] 2023-05-28 13:35
Sorry, I missed your answer.

> Do you have to have undefined in there for this to be a reproducer?

No, I tried with real values, and it still reproduces.

**Comment by zliu41** [comment] 2023-08-15 19:10
@uhbif19 I tried something similar to what you did on master and couldn't reproduce. It would be helpful if you can confirm whether this is still a problem on 1.10.0.0 (or a recent version), if not on master. And if it is, try adding `{-# OPTIONS_GHC -fomit-interface-pragmas #-}` in `PlutusTx.Plugin.Utils` (the module where `plc` is defined).

**Comment by effectfully** [comment] 2023-11-22 11:30
We don't have a reproducer and it's been 3 months since the last message, hence I'm going to close this ticket. Do feel free to reopen any time.

**Closed by effectfully** 2023-11-22 11:30 UTC
Labels: bug, status: needs info from the reporter
