### ISSUE TITLE
utxoAt hangs in the PAB when trying to read user's own TxOutRef's (attached to ownPubKey)

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3596] opened 2021-07-22 16:52 UTC
## Area

* *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
* *Other* Any other topic (Playgrounds, etc.)

## Summary

When running code in PAB I experience hang on `utxoAt` when trying to read my own 
UTXO's attached on user's address. It hangs and then starts to get on  fast growing space leak.

the code was working. But stopped to work when I have upgraded on the latest plutus version.

## Steps to reproduce

I have a function:

```haskell
 withNftTxOutRef :: (TxOutRef -> TxOutTx -> Contract w schema Text ()) -> Contract w schema Text ()
 withNftTxOutRef cont = do
   logInfo @String "A"
   pkh <- pubKeyHash <$> ownPubKey
   logInfo @String "B"
   orefs <- M.toList <$> utxoAt (pubKeyHashAddress pkh)
   logInfo @String "C"
   case orefs of
     []       -> logInfo @String "No UTXO found"
     (oref, txOut) : _ -> do
       logInfo @String "D"
       cont oref txOut
```

It prints only "A" and "B".

## Expected behavior

No hang on utxoAt, no space leak.

**Comment by luigy** [comment] 2021-07-22 17:10
Hi @anton-k, do you have the rev handy of the last time it was working?

**Comment by anton-k** [comment] 2021-07-22 17:33
@luigy quite old but I guess it was working on:

```"f0f3e905c449865abb0afedd2dbbb33a10c78aa5"```

**Comment by luigy** [comment] 2021-07-22 20:39
I cant repro on 982dd8b51896b35e70a8c1cd22e3faf5dd479c20
```sh
[INFO] Slot 0: TxnValidate b135806142f3d020fc68e9e72fa6e8e7c8fce34b2a0f17fd23b633641f58944a
[INFO] Running
[INFO] 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00: "A"
[INFO] 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00: "B"
[INFO] 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00: "C"
[INFO] 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00: "D"
[INFO] Activated instance 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00 on W1
[INFO] ContractInstanceId {unContractInstanceId = 4bc660a3-af56-45a0-8abc-ee0d0f0e3e00}
Success
```
```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE FlexibleContexts #-}
module Main where

import           Control.Monad.Freer (Eff, Member, interpret, type (~>))
import           Control.Monad.Freer.Error (Error)
import           Control.Monad.Freer.Extras.Log      (LogMsg)
import           Data.Aeson
import           Data.Default
import qualified Data.Map as M
import           Data.Text (Text)
import           Data.Text.Prettyprint.Doc
import           Ledger
import           Plutus.Contract
import           Plutus.PAB.Core (EffectHandlers)
import           Plutus.PAB.Effects.Contract.Builtin (Builtin, SomeBuiltin(..))
import           Plutus.PAB.Types (PABError)
import           Plutus.PAB.Effects.Contract (ContractEffect (..))
import qualified Plutus.PAB.Effects.Contract.Builtin as Builtin
import qualified Plutus.PAB.Simulator as Simulator
import           Plutus.PAB.Simulator (Simulation, SimulatorContractHandler, SimulatorState, mkSimulatorHandlers, runSimulationWith, logString)
import           Playground.Types (FunctionSchema(..))
import           Schema (FormSchema)
import           GHC.Generics
import           Plutus.PAB.Monitoring.PABLogMsg (PABMultiAgentMsg)
import           Wallet.Emulator.Types (Wallet(..))

main :: IO ()
main = do
  res <- runSimulation $ do
    logString @(Builtin TestContracts) "Running"
    i  <- Simulator.activateContract (Wallet 1) Issue3596
    logString @(Builtin TestContracts) $ show i
  case res of
      Left err -> print err
      Right _ -> putStrLn "Success"

issue3596 :: (TxOutRef -> TxOutTx -> Contract () EmptySchema Text ()) -> Contract () EmptySchema Text ()
issue3596 cont = do
   logInfo @String "A"
   pkh <- pubKeyHash <$> ownPubKey
   logInfo @String "B"
   orefs <- M.toList <$> utxoAt (pubKeyHashAddress pkh)
   logInfo @String "C"
   case orefs of
     []       -> logInfo @String "No UTXO found"
     (oref, txOut) : _ -> do
       logInfo @String "D"
       cont oref txOut

data TestContracts = Issue3596
  deriving (Eq, Ord, Show, Generic)
  deriving anyclass (FromJSON, ToJSON)

instance Pretty TestContracts where
  pretty = viaShow

simulatorHandlers :: EffectHandlers (Builtin TestContracts) (SimulatorState (Builtin TestContracts))
simulatorHandlers = mkSimulatorHandlers @(Builtin TestContracts) def [Issue3596] handler where
    handler :: SimulatorContractHandler (Builtin TestContracts)
    handler = interpret handleContractTest

runSimulation :: Simulation (Builtin TestContracts) a -> IO (Either PABError a)
runSimulation = runSimulationWith @(Builtin TestContracts) simulatorHandlers

handleContractTest ::
  ( Member (Error PABError) effs
  , Member (LogMsg (PABMultiAgentMsg (Builtin TestContracts))) effs
  )
  => ContractEffect (Builtin TestContracts)
  ~> Eff effs
handleContractTest = Builtin.handleBuiltin getSchema getContract

getSchema :: TestContracts -> [FunctionSchema FormSchema]
getSchema = \case
  Issue3596 -> Builtin.endpointsToSchemas @EmptySchema

getContract :: TestContracts -> SomeBuiltin
getContract = \case
  Issue3596 -> SomeBuiltin (issue3596 (\_ _ -> return ()))
```

**Comment by anton-k** [comment] 2021-07-23 08:00
Unfortunately I can not share my code, because it's private. 
Maybe I will be able to provide minimal example.

**Comment by anton-k** [comment] 2021-07-23 13:01
I'm sorry to say but today I've got the same issue with `observableState`.
I suspect that it does not hangs but throws an exceptions that is not handled.

**Comment by anton-k** [comment] 2021-07-23 13:01
As a result program silently breaks, and it's really frustrating experience.

**Comment by sorki** [comment] 2021-07-23 13:45
> I'm sorry to say but today I've got the same issue with call to `observableState`.
> I suspect that it does not hang but throws an exception that is not handled.

Looks like a PR possibly fixing that one just landed https://github.com/input-output-hk/plutus/pull/3604

**Comment by ak3n** [comment] 2021-07-26 09:40
Please, try `Plutus.Contract.Types.handleError` to handle the exceptions and get the error details:

```
import Plutus.Contract

handleError logError $ contract
```

**Comment by ak3n** [comment] 2021-08-03 09:06
I'm closing this issue because it seems that the PR fixed the problem with `observableState`, while the original problem was not reproduced.

Please feel free to re-open or ask questions.

**Closed by ak3n** 2021-08-03 09:06 UTC
Labels: bug
